config/routes.rb
  Rails.application.routes.draw do
  resources :carousels
  resources :user_providers
  

  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  get 'uploads/create'
  post 'uploads' => 'uploads#create'
  resources :regions
  get "/route", to: "payments#route"
  delete "/route", to: "payments#destroy"
  get "/buys", to: "payments#buys"	
  get "payments/express"
  get "transactions/checkout"
  resources :payments
  resources :searches
  resources :contacts, only: [:new, :create]

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :deals, :regions, :categories, :payments, :route, :contacts do
      resources :questions, only: [:create, :destroy, :update]  
    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: :get
    match '', to: redirect("/#{I18n.default_locale}"), via: :get
  end    
      
  
  resources :categories 
  resources :destinations do
    resources :comments, only: [:create, :destroy, :update] 
  end
 get 'welcome/index'
 root 'destinations#index'
 get 'deals/index'

 get "/dashboard", to: "welcome#dashboard"

 put "/destinations/:id/publish", to: "destinations#publish"

  get "/sales", to: "welcome#sales"
  get "/followup", to: "welcome#followup"
  get "/about", to: "welcome#about"
  get "/privacy", to: "welcome#privacy"
  get "/terms", to: "welcome#terms"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_provider.rb
class UserProvider < ApplicationRecord
  belongs_to :user

  def self.find_for_facebook_oauth(auth)

        user = UserProvider.where(:provider => auth.provider, :uid => auth.uid).first
        unless user.nil?
            user.user
        else
            registered_user = User.where(:email => auth.info.email).first
            unless registered_user.nil?
                        UserProvider.create!(
                              provider: auth.provider,
                              uid: auth.uid,
                              user_id: registered_user.id
                              )
                registered_user
            else
                user = User.create!(
                    name: auth.info.name,
                            email: auth.info.email,
                            password: Devise.friendly_token[0,20],
                            )
                user_provider = UserProvider.create!(
                    provider:auth.provider,
                            uid:auth.uid,
                              user_id: user.id
                    )
                user
            end
        end
    end

    def self.find_for_google_oauth(auth)
        user = UserProvider.where(:provider => auth.provider, :uid => auth.uid).first
        unless user.nil?
            user.user
        else
            registered_user = User.where(:email => auth.info.email).first
            unless registered_user.nil?
                        UserProvider.create!(
                              provider: auth.provider,
                              uid: auth.uid,
                              user_id: registered_user.id
                              )
                registered_user
            else
                user = User.create!(
                    name: auth.info.name,
                              email: auth.info.email,
                              password: Devise.friendly_token[0,20],
                            )
                user_provider = UserProvider.create!(
                    provider:auth.provider,
                            uid:auth.uid,
                            user_id: user.id
                    )
                user
            end
        end
    end

  
end

app/controllers/user_providers_controller.rb
class UserProvidersController < ApplicationController
  before_action :set_user_provider, only: [:show, :edit, :update, :destroy]

  # GET /user_providers
  # GET /user_providers.json
  def index
    @user_providers = UserProvider.all
  end

  # GET /user_providers/1
  # GET /user_providers/1.json
  def show
  end

  # GET /user_providers/new
  def new
    @user_provider = UserProvider.new
  end

  # GET /user_providers/1/edit
  def edit
  end

  # POST /user_providers
  # POST /user_providers.json
  def create
    @user_provider = UserProvider.new(user_provider_params)

    respond_to do |format|
      if @user_provider.save
        format.html { redirect_to @user_provider, notice: 'User provider was successfully created.' }
        format.json { render :show, status: :created, location: @user_provider }
      else
        format.html { render :new }
        format.json { render json: @user_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_providers/1
  # PATCH/PUT /user_providers/1.json
  def update
    respond_to do |format|
      if @user_provider.update(user_provider_params)
        format.html { redirect_to @user_provider, notice: 'User provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_provider }
      else
        format.html { render :edit }
        format.json { render json: @user_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_providers/1
  # DELETE /user_providers/1.json
  def destroy
    @user_provider.destroy
    respond_to do |format|
      format.html { redirect_to user_providers_url, notice: 'User provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_provider
      @user_provider = UserProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_provider_params
      params.require(:user_provider).permit(:user_id, :provider, :uid)
    end
end

app/helpers/user_providers_helper.rb
module UserProvidersHelper
end

app/views/user_providers/_form.html.erb
<%= simple_form_for(@user_provider) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :provider %>
    <%= f.input :uid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_providers/edit.html.erb
<h1>Editing User Provider</h1>

<%= render 'form', user_provider: @user_provider %>

<%= link_to 'Show', @user_provider %> |
<%= link_to 'Back', user_providers_path %>

app/views/user_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Providers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_providers.each do |user_provider| %>
      <tr>
        <td><%= user_provider.user %></td>
        <td><%= user_provider.provider %></td>
        <td><%= user_provider.uid %></td>
        <td><%= link_to 'Show', user_provider %></td>
        <td><%= link_to 'Edit', edit_user_provider_path(user_provider) %></td>
        <td><%= link_to 'Destroy', user_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Provider', new_user_provider_path %>

app/views/user_providers/new.html.erb
<h1>New User Provider</h1>

<%= render 'form', user_provider: @user_provider %>

<%= link_to 'Back', user_providers_path %>

app/views/user_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_provider.user %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @user_provider.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user_provider.uid %>
</p>

<%= link_to 'Edit', edit_user_provider_path(@user_provider) %> |
<%= link_to 'Back', user_providers_path %>