config/routes.rb
  Rails.application.routes.draw do
  resources :carousels
  resources :user_providers
  

  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  get 'uploads/create'
  post 'uploads' => 'uploads#create'
  resources :regions
  get "/route", to: "payments#route"
  delete "/route", to: "payments#destroy"
  get "/buys", to: "payments#buys"	
  get "payments/express"
  get "transactions/checkout"
  resources :payments
  resources :searches
  resources :contacts, only: [:new, :create]

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :deals, :regions, :categories, :payments, :route, :contacts do
      resources :questions, only: [:create, :destroy, :update]  
    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: :get
    match '', to: redirect("/#{I18n.default_locale}"), via: :get
  end    
      
  
  resources :categories 
  resources :destinations do
    resources :comments, only: [:create, :destroy, :update] 
  end
 get 'welcome/index'
 root 'destinations#index'
 get 'deals/index'

 get "/dashboard", to: "welcome#dashboard"

 put "/destinations/:id/publish", to: "destinations#publish"

  get "/sales", to: "welcome#sales"
  get "/followup", to: "welcome#followup"
  get "/about", to: "welcome#about"
  get "/privacy", to: "welcome#privacy"
  get "/terms", to: "welcome#terms"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carousel.rb
class Carousel < ApplicationRecord
	translates :body, :carouselpic, :carouselpic1, :carouselpic2, :carouselpic3

	has_attached_file :carouselpic, styles: { medium: "1280x720", thumb: "800x600"}
    validates_attachment_content_type :carouselpic, content_type: /\Aimage\/.*\Z/

    has_attached_file :carouselpic1, styles: { medium: "1280x720", thumb: "800x600"}
    validates_attachment_content_type :carouselpic, content_type: /\Aimage\/.*\Z/

    has_attached_file :carouselpic2, styles: { medium: "1280x720", thumb: "800x600"}
    validates_attachment_content_type :carouselpic2, content_type: /\Aimage\/.*\Z/


    has_attached_file :carouselpic3, styles: { medium: "1280x720", thumb: "800x600"}
    validates_attachment_content_type :carouselpic3, content_type: /\Aimage\/.*\Z/
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
 before_action :set_carousel, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_editor!, only: [:new,:create,:update,:edit]
 before_action :authenticate_admin!, only: [:destroy, :show, :index]

  # GET /carousels
  # GET /carousels.json
  def index
    @carousels = Carousel.all
  end

  # GET /carousels/1
  # GET /carousels/1.json
  def show
  end

  # GET /carousels/new
  def new
    @carousel = Carousel.new
  end

  # GET /carousels/1/edit
  def edit
  end

  # POST /carousels
  # POST /carousels.json
  def create
    @carousel = Carousel.new(carousel_params)

    respond_to do |format|
      if @carousel.save
        format.html { redirect_to @carousel, notice: 'Carousel was successfully created.' }
        format.json { render :show, status: :created, location: @carousel }
      else
        format.html { render :new }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carousels/1
  # PATCH/PUT /carousels/1.json
  def update
    respond_to do |format|
      if @carousel.update(carousel_params)
        format.html { redirect_to @carousel, notice: 'Carousel was successfully updated.' }
        format.json { render :show, status: :ok, location: @carousel }
      else
        format.html { render :edit }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carousels/1
  # DELETE /carousels/1.json
  def destroy
    @carousel.destroy
    respond_to do |format|
      format.html { redirect_to carousels_url, notice: 'Carousel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carousel
      @carousel = Carousel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carousel_params
      params.require(:carousel).permit(:body, :carouselpic, :carouselpic1, :carouselpic2, :carouselpic3)
    end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/views/carousels/_form.html.erb
<%= simple_form_for(@carousel) do |f| %>
	<div class="centerforms">
	 <%= f.error_notification %>

	 <div class="form-inputs">
	   <%= f.input :body %>
	 </div>
	 


	 
	   Imagen 1: <%= f.file_field :carouselpic %>

	   Imagen 2: <%= f.file_field :carouselpic1 %>
	 
	   Imagen 3: <%= f.file_field :carouselpic2 %>
	 
	   Imagen 4: <%= f.file_field :carouselpic3 %>
	 

	 <div class="form-actions">
	   <%= f.button :submit %>
	 </div>
	<% end %>
</div>

app/views/carousels/edit.html.erb
<h1>Editing Carousel</h1>

<%= render 'form', carousel: @carousel %>

<%= link_to 'Show', @carousel %> |
<%= link_to 'Back', carousels_path %>

app/views/carousels/index.html.erb
<div class="centerforms">
<% if signed_in? && current_user.is_admin? %>




<p id="notice"><%= notice %></p>

<h1>Carousels</h1>

<table>
 <thead>
   <tr>
     <th>Body</th>
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @carousels.each do |carousel| %>
     <tr>
       <td><%= carousel.body %></td>
       <td><%= image_tag carousel.carouselpic.url(), :class => "carouselindeximages" %></td>
       <td><%= image_tag carousel.carouselpic1.url(), :class => "carouselindeximages" %></td>
       <td><%= image_tag carousel.carouselpic2.url(), :class => "carouselindeximages" %></td>
       <td><%= image_tag carousel.carouselpic3.url(), :class => "carouselindeximages" %></td>
       <td><%= link_to 'Show', carousel %></td>
       <td><%= link_to 'Edit', edit_carousel_path(carousel) %></td>
       <td><%= link_to 'Destroy', carousel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
   <% end %>
 </tbody>
</table>

<br>

<%= link_to 'New Carousel', new_carousel_path %>
<%else%>
<div class="nothing"></div>
<%end%>

</div>

app/views/carousels/new.html.erb
<h1>New Carousel</h1>

<%= render 'form', carousel: @carousel %>

<%= link_to 'Back', carousels_path %>

app/views/carousels/show.html.erb
<% if signed_in? && current_user.is_admin? %>
<p id="notice"><%= notice %></p>

<p>
 <strong>Body:</strong>
    <%= image_tag @carousel.carouselpic.url() %>
    <%= image_tag @carousel.carouselpic1.url() %>
    <%= image_tag @carousel.carouselpic2.url() %>
    <%= image_tag @carousel.carouselpic3.url() %>


</p>

<%= link_to 'Edit', edit_carousel_path(@carousel) %> |
<%= link_to 'Back', carousels_path %>

<%else%>
<div class="nothing"></div>
<%end%>