config/routes.rb
  Rails.application.routes.draw do
  resources :carousels
  resources :user_providers
  

  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  get 'uploads/create'
  post 'uploads' => 'uploads#create'
  resources :regions
  get "/route", to: "payments#route"
  delete "/route", to: "payments#destroy"
  get "/buys", to: "payments#buys"	
  get "payments/express"
  get "transactions/checkout"
  resources :payments
  resources :searches
  resources :contacts, only: [:new, :create]

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :deals, :regions, :categories, :payments, :route, :contacts do
      resources :questions, only: [:create, :destroy, :update]  
    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: :get
    match '', to: redirect("/#{I18n.default_locale}"), via: :get
  end    
      
  
  resources :categories 
  resources :destinations do
    resources :comments, only: [:create, :destroy, :update] 
  end
 get 'welcome/index'
 root 'destinations#index'
 get 'deals/index'

 get "/dashboard", to: "welcome#dashboard"

 put "/destinations/:id/publish", to: "destinations#publish"

  get "/sales", to: "welcome#sales"
  get "/followup", to: "welcome#followup"
  get "/about", to: "welcome#about"
  get "/privacy", to: "welcome#privacy"
  get "/terms", to: "welcome#terms"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deal.rb
class Deal < ApplicationRecord
  translates :place, :description, :details, :other_details, :policies_and_fees, :price
  belongs_to :user
  belongs_to :destination
  has_many :questions, dependent: :nullify

  #has_many :has_regions
  #has_many :regions, through: :has_regions

  has_many :has_packages, dependent: :nullify
  has_many :destinations, through: :has_packages, dependent: :nullify

  has_many :payments, dependent: :delete_all
  validates :place, presence: true, uniqueness: true
  #after_create :save_regions
  before_save :default_price

  has_attached_file :pic, styles: { medium: "1280x720", thumb: "800x600"}
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\Z/
  
  has_attached_file :pic1, styles: { medium: "1280x720", thumb: "800x600"}
  validates_attachment_content_type :pic1, content_type: /\Aimage\/.*\Z/
  

  #def regions=(value)
    #@regions = value
  #end
  
  	def default_price
  		self.price ||= 0
	end

	def user_already_paid? user_id
		self.payments.where(state:2).size > 0
	end

  private

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show,:index]
  before_action :authenticate_editor!, only: [:new,:create,:update,:edit]
  before_action :authenticate_admin!, only: [:destroy]
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @question = Question.new
  end

  # GET /deals/new
  def new
    @deal = Deal.new
    @regions = Region.all
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = current_user.deals.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:place, :description, :details, :other_details, :policies_and_fees, :price, :user_id, :regions, :pic, :pic1,:video_deal, :currency,:destination_id, :category)
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deal.html.erb
  <div class="col-sm-6 col-md-4 col-lg-3">
    <div class="thumbnail">
          
         
        <%= link_to deal do %>
   <%= image_tag deal.pic.url() %>
<% end %>
          
          
            
        
          
      
     
      <div class="caption">
        <h3><%= link_to deal.place, deal %></h3>
        <p>
          <%=truncate(deal.details,length:90) %>
          <%=link_to (t ".read"), deal%>
        </p>
        <div class="btn-group">
                
            <button type="button" class="btn btn-success"><%= link_to (t ".apply"), deal %></button>
            <% if signed_in? && current_user.is_admin? %>
            <button type="button" class="btn btn-primary"><%= deal.destination_id %></button>
            <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_deal_path(deal) %></button>
            <button type="button" class="btn btn-danger"><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          
               <% else %>
          <div class="nothing"></div>
            <% end %>
        </div>
      </div>
    </div>
  </div>

 

app/views/deals/_form.html.erb
<%= simple_form_for(@deal) do |f| %>

<% if deal.errors.any? %>
<div class="centerforms">
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

  <div class="field">
    <%= f.label :place %>
    <%= f.text_area :place%>
  </div>

  <div class="field">
    <%= f.input :description %>
  </div>

  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>

  <div class="field">
    <%= f.label :other_details %>
    <%= f.text_area :other_details %>
  </div>

  <div class="field">
    <%= f.label :policies_and_fees %>
    <%= f.text_area :policies_and_fees %>
  </div>
  
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price, step: "any" %>
  </div>

  
 <div class="field">
    <%=f.label :currency %>
    <%= f.text_area :currency, step: "any"%>
 </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    Fotos: <%= f.file_field :pic %>
  </div>

  <div class="field">
    Fotos: <%= f.file_field :pic1 %>
  </div>

  <div class="field">
    <%= f.input :video_deal %>
  </div>
  
  <div class="field">
    <%= f.label :destination_id %>
  </div>

  <div class="field">
    <%= collection_select( :deal, :destination_id, Destination.all, :id, :place, {}, {:multiple => false } )%>
  </div>

  <div class="actions">
    <%= f.submit %>

  </div>
  </div>
<% end %>
<!-- <script type="text/javascript">
  $(document).ready(function() {
    $('#summernote').summernote();
  });
</script> -->

app/views/deals/edit.html.erb
<div class="centerforms">
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>
</div>

app/views/deals/index.html.erb
<div class="img-deals">
  
  <h3><%= t ".outlet" %></h3>

<p id="notice alert"><%= notice %></p>
</div>



<div class="container-fluid options2">
    <nav class="breadcrumb">
      <li><%= link_to "Home", destinations_path, :class => "breadcrumb-item" %> </li>
      <li><span class="breadcrumb-item active"><%= t ".hotdeals" %></span></li>
    </nav>
  <div class="row main-rows">

 <%= render @deals %> 
 </div>  
</div> <!-- container -->
<!-- <script>
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
});
      // For Demo purposes only (show hover effect on mobile devices)
      [].slice.call( document.querySelectorAll('a[href="#"') ).forEach( function(el) {
        el.addEventListener( 'click', function(ev) { ev.preventDefault(); } );
      } );


</script> -->

<hr class="style-two">


</div>

app/views/deals/new.html.erb
<div class="centerforms">
<h1>CREATE A  NEW DEAL</h1>
<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>
</div>

app/views/deals/show.html.erb
<br>
<br>
<br>
<br>
<p id="notice"><%= notice %></p>
<div class="container-fluid">
 
    <nav class="breadcrumb">
      <li><%= link_to "Home", destinations_path, :class => "breadcrumb-item" %> </li>
      <li><%= link_to (t ".HotDeals"), deals_path, :class => "breadcrumb-item" %> </li>
      <li><span class="breadcrumb-item active"><%= t ".check" %></span></li>
          
    </nav>
  
  <div id="place-img-reservation" class="row">
    <div id="price" class="row">
      <div class="col-md-12">
      <h1><%= t ".just_for" %> &nbsp <%= @deal.currency %> &nbsp<%= @deal.price %></h1>
      </div>
    </div>
    <div id="deal-img-reservation" class="row">

      <div class="col-md-8">  <!--imgs deals -->
      <div id="inner-deal-img">
      <div id="deal-name">
        <h1><%= @deal.place %></h1>

      </div>
        
        <div class="owl-carousel owl-theme">
            
            <div class="item">
              
              <div class="deal2-img">
          
          <% if @deal.other_details.blank? %>
            
            <div class="nothing"></div>
            
          
               <% else %>
           <div class="deal2-promo ">
                <%= @deal.other_details %>
                </div>
            <% end %>


               
                
                <%= image_tag @deal.pic.url() %>
              </div> <!-- deal2-img -->

            </div> <!-- item -->
            <div class="item">
              
              <div class="deal2-img">
                
                <div class="deal2-promo">
                <%= @deal.other_details %>
                </div>
                
                <%= image_tag @deal.pic1.url() %>
              </div> <!-- deal2-img -->
              
            </div> <!-- item -->
            <div class="item">
              <%= @deal.video_deal %>
            </div>

          </div><!--  owl theme -->
      
      </div><!--  inner-deal-img -->

      </div> <!-- col-md-6 -->
      
      <div id="reservation-hotdeal" class="col-md-4">
        <div id="inner-reservation-hotdeal">
          <div id="buy-now"> 
            <h2><strong><%= t ".book" %></strong></h2>
          </div>
          <br> <!-- pilas con este break...es temporal -->
          <div id="reservation">
            <!--< if !user_signed_in? %>
              < render "payments/form", payment: Payment.new, deal: @deal %>
            < end %>
            < if user_signed_in? %>
              < if @deal.user_already_paid? current_user.id %>
              < else %> -->
                <%= render "payments/form", payment: Payment.new, deal: @deal %>
              <!--< end %>
            < end %>-->
            
          </div>
        </div>
      </div><!--  reservation-hotdeal -->
    </div><!-- deal-img-reservation -->
  </div><!-- place-img-reservation End-->

  <!-- DEAL DETAIL -->
<div class="details_deals">
          <%= @deal.details %>
        </div>

  <!-- END DEAL DETAIL -->



  <div id="specification-deal">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" data-parent="false">
  <div class="panel panel-default">
    <div class="panel-heading panel-heading_proper" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <%= t ".description" %>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%= @deal.description  %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading panel-heading_proper" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <%= t ".policies_and_fees" %>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
      
        <%= @deal.policies_and_fees %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading panel-heading_proper" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <%= t ".questions" %>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
      
        <% @deal.questions.each do |question| %>
        <div class="media">
        
          <div class="media-left">
           
       <%= image_tag "avatar.jpeg", :alt => "", :class => "media-object avatar-rupgo-question_deal" %>
            
          </div>
  <div class="media-body">
    <h4 class="media-heading"><%= t ".question" %></h4>
    <%= question.body %>
  </div>

</div>
      <% end %>  
       
        <%= render "questions/form" %>
      </div>
    </div>
  </div>


</div>
  </div>

<%= link_to (t ".back"), deals_path %>
</div> <!-- end Container fluid -->
<script>
$( ".deal2-promo:empty" )
  .text( "Was empty!" )
  .css( "background", "rgb(255,220,200)" );
</script>
</script>
<script>
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:0,
    nav:false,
    dots: true,
    stagePadding: 0,
    
    lazyLoad: true,
    
    video: true,
    
    

    
    
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
});
     

</script>